--INSERT INTO USERS.DEPARTMENT VALUES (NEXTVAL('USERS_SEQUENCE'),'ПТО');
--INSERT INTO USERS.DEPARTMENT VALUES (NEXTVAL('USERS_SEQUENCE'),'ПТО');
INSERT INTO USERS.LOGBOOK_USER_ROLE_DICTIONARY (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Администратор','Добавление пользователей.Редактирование.Назначение прав');
INSERT INTO USERS.LOGBOOK_USER_ROLE_DICTIONARY (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Редактор','Редактирование и просмотр записей');
INSERT INTO USERS.LOGBOOK_USER_ROLE_DICTIONARY (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Читатель','Просмотр записей');
INSERT INTO USERS.LOGBOOK_USER_ROLE_DICTIONARY (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Член приемочной комиссии','Просмотр записей');
INSERT INTO USERS.LOGBOOK_USER_ROLE_DICTIONARY (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Председатель приемочной комиссии','Просмотр записей');
INSERT INTO USERS.LOGBOOK_USER_ROLE_DICTIONARY (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Поверитель','Просмотр записей');
INSERT INTO USERS.LOGBOOK_USER_ROLE_DICTIONARY (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Проверяющий','Просмотр записей');
INSERT INTO USERS.LOGBOOK_USER_ROLE_DICTIONARY (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Технический специалист','Просмотр записей');
