--INSERT INTO USERS.DEPARTMENT VALUES (NEXTVAL('USERS_SEQUENCE'),'ПТО');
--INSERT INTO USERS.DEPARTMENT VALUES (NEXTVAL('USERS_SEQUENCE'),'ПТО');
INSERT INTO USERS.LOGBOOK_USER_ROLE (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Администратор','Добавление пользователей.Редактирование.Назначение прав');
INSERT INTO USERS.LOGBOOK_USER_ROLE (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Редактор','Редактирование и просмотр записей');
INSERT INTO USERS.LOGBOOK_USER_ROLE (LOGBOOK_USER_ROLE_NAME,LOGBOOK_USER_ROLE_DESC)
   VALUES ('Читатель','Просмотр записей');