
DROP SCHEMA IF EXISTS USERS;
DROP SEQUENCE IF EXISTS USERS_SEQUENCE;


CREATE SCHEMA IF NOT EXISTS USERS;
CREATE SEQUENCE IF NOT EXISTS USERS_SEQUENCE;

CREATE TABLE IF NOT EXISTS USERS.DEPARTMENT(DEPARTMENT_ID INT, DEPARTMENT_NAME VARCHAR(60) NOT NULL,
                                      CONSTRAINT PK_DEPARTMENT_ID PRIMARY KEY (DEPARTMENT_ID),
                                      CONSTRAINT UN_DEPARTMENT_NAME UNIQUE (DEPARTMENT_NAME)
                                      );

CREATE TABLE IF NOT EXISTS USERS.JOBTITLE(JOBTITLE_ID INT, JOBTITLE_NAME VARCHAR(60) NOT NULL,
                                          CONSTRAINT PK_JOBTITLE_ID PRIMARY KEY (JOBTITLE_ID),
                                          CONSTRAINT UN_JOBTITLE_ID UNIQUE (JOBTITLE_ID)
                                          );

CREATE TABLE IF NOT EXISTS USERS.ORGANIZATION(ORGANIZATION_ID INT,
                                              ORGANIZATION_NAME VARCHAR(60) NOT NULL,
                                              ORGANIZATION_DESC VARCHAR(256),
                                              CONSTRAINT PK_ORGANIZATION_ID PRIMARY KEY (ORGANIZATION_ID),
                                              CONSTRAINT UN_ORGANIZATION_NAME UNIQUE (ORGANIZATION_NAME)
);

CREATE TABLE IF NOT EXISTS USERS.LOGBOOK_USER_ROLE(LOGBOOK_USER_ROLE_ID INT DEFAULT NEXTVAL('USERS_SEQUENCE'),
                                                   LOGBOOK_USER_ROLE_NAME VARCHAR(45) NOT NULL,
                                                   LOGBOOK_USER_ROLE_DESC VARCHAR(256),
                                                   CONSTRAINT PK_LOGBOOK_USER_ROLE_ID PRIMARY KEY (LOGBOOK_USER_ROLE_ID),
                                                   CONSTRAINT UN_LOGBOOK_USER_ROLE_NAME UNIQUE (LOGBOOK_USER_ROLE_NAME)

);

